//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Get.the.solution.Image.Manipulation.Localization {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Get.the.solution.Image.Manipulation.Localization.AppResources", typeof(AppResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Resizer.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resize the orginal pictures (don&apos;t create copies).
        /// </summary>
        public static string CopyEnabled {
            get {
                return ResourceManager.GetString("CopyEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Easy Resize Images Resize Image by starting the app. Select the image you want to resize. Or Right click on image file, select open with Image Resizer. Support for .jpg, .png, .gif, .bmp You also can send the resized image via email, by sharing the image..
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are sorry but something unexpected happend :(. We added the error to the Clipboard (Get it with CTR+V) Please send us the error exception. Exception: {0}.
        /// </summary>
        public static string ExceptionOnResize {
            get {
                return ResourceManager.GetString("ExceptionOnResize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The setting of the &quot;Resize the orginal pictures (don&apos;t create copies)&quot; checkbox will be saved for your next session..
        /// </summary>
        public static string HelpAutoSave {
            get {
                return ResourceManager.GetString("HelpAutoSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Did you know?.
        /// </summary>
        public static string HelpDidYouKnow {
            get {
                return ResourceManager.GetString("HelpDidYouKnow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double Tappe an image to open it..
        /// </summary>
        public static string HelpDoubleTap {
            get {
                return ResourceManager.GetString("HelpDoubleTap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First select an image and then set the proper size. Click ok to save the resized image..
        /// </summary>
        public static string HelpFromShell {
            get {
                return ResourceManager.GetString("HelpFromShell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resize an image from windows explorer. Right click on image. select open with &quot;Image Resizer&quot;..
        /// </summary>
        public static string HelpFromShellHow {
            get {
                return ResourceManager.GetString("HelpFromShellHow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When you selected the wrong image file to resize you can select it and press &quot;DEL&quot; to remove it from the list..
        /// </summary>
        public static string HelpRemoveImage {
            get {
                return ResourceManager.GetString("HelpRemoveImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string HelpTitle {
            get {
                return ResourceManager.GetString("HelpTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep aspect ratio.
        /// </summary>
        public static string KeepAspectRatio {
            get {
                return ResourceManager.GetString("KeepAspectRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resize Image with Image Resizer.
        /// </summary>
        public static string OpenWith {
            get {
                return ResourceManager.GetString("OpenWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can create resized copies of one selected picture and store them in your prefered folder..
        /// </summary>
        public static string Resize {
            get {
                return ResourceManager.GetString("Resize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save As.
        /// </summary>
        public static string SaveAs {
            get {
                return ResourceManager.GetString("SaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Image.
        /// </summary>
        public static string SelectImage {
            get {
                return ResourceManager.GetString("SelectImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a size:.
        /// </summary>
        public static string SelectSize {
            get {
                return ResourceManager.GetString("SelectSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share (e.g for Email).
        /// </summary>
        public static string Share {
            get {
                return ResourceManager.GetString("Share", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to open the last modified file?.
        /// </summary>
        public static string ShowLastFile {
            get {
                return ResourceManager.GetString("ShowLastFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to by.
        /// </summary>
        public static string SizeCustomBy {
            get {
                return ResourceManager.GetString("SizeCustomBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  screen).
        /// </summary>
        public static string SizeCustomHeight {
            get {
                return ResourceManager.GetString("SizeCustomHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom (fits a .
        /// </summary>
        public static string SizeCustomWidth {
            get {
                return ResourceManager.GetString("SizeCustomWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium (fits a 800 x 600 screen).
        /// </summary>
        public static string SizeMedium {
            get {
                return ResourceManager.GetString("SizeMedium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to by.
        /// </summary>
        public static string SizePercentBy {
            get {
                return ResourceManager.GetString("SizePercentBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %).
        /// </summary>
        public static string SizePercentHeight {
            get {
                return ResourceManager.GetString("SizePercentHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percent (fits a.
        /// </summary>
        public static string SizePercentWidth {
            get {
                return ResourceManager.GetString("SizePercentWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Small (fits a 640 x 480 screen).
        /// </summary>
        public static string SizeSmall {
            get {
                return ResourceManager.GetString("SizeSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
